# It once was managed by molecule, but there's an issue with that
# https://github.com/ansible/molecule/issues/3773
# https://ansible.readthedocs.io/projects/molecule/guides/custom-image/

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN \
  if [ $(command -v apt-get) ]; then \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y bash curl dirmngr iproute2 python3 python3-apt procps sudo systemd systemd-sysv vim \
    && apt-get clean; \
  elif [ $(command -v dnf) ]; then \
    dnf makecache \
    && dnf --assumeyes install bash iproute sudo systemd /usr/bin/python3 /usr/bin/python3-config vim \
    && dnf clean all; \
  elif [ $(command -v zypper) ]; then \
    zypper refresh \
    && zypper install -y bash iproute2 python3 sudo systemd systemd-sysvinit vim \
    && zypper clean -a; \
  elif [ $(command -v apk) ]; then \
    apk update \
    && apk add --no-cache bash curl openrc python3 sudo vim; \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf; \
  elif [ $(command -v xbps-install) ]; then \
    xbps-install -Syu \
    && xbps-install -y bash iproute2 python3 sudo vim \
    && xbps-remove -O; \
  fi

