---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker yamllint

      #- name: Run yamllint.
      #  run: yamllint .

      #- name: Run ansible-lint.
      #  uses: ansible/ansible-lint@main # or version tag instead of 'main'


      - name: Run Molecule tests.
        run: molecule test
        env:
          # colors are nice when the output is short
          PY_COLORS: '1'  # for molecule
          ANSIBLE_FORCE_COLOR: '1'  # for ansible
