---
name: CI
'on':
  pull_request:
  push:
    branches:
      - test/molecule

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker yamllint ansible-lint

      # - name: Lint the codebase.
      #   run: |
      #     yamllint . \
      #     ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          # colors are nice when the output is short
          PY_COLORS: '1'  # for molecule
          ANSIBLE_FORCE_COLOR: '1'  # for ansible
